markdown: kramdown
highlighter: rouge
baseurl: "/programming-lessons"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-themes

collections:
  rust-from-zero:
    output: true
    permalink: /rust-from-zero/:path/

defaults:
  - scope:
      type: rust-from-zero
    values:
      layout: default
