markdown: kramdown
highlighter: rouge
baseurl: "/programming-lessons"
remote_theme: midnight

collections:
  rust-from-zero:
    output: true
    permalink: /rust-from-zero/:path/

defaults:
  - scope:
      type: rust-from-zero
    values:
      layout: default
